# show coverage in CI status, not as a comment.
comment: off
fixes:
  - "*/site-packages/::"
coverage:
  status:
    project:
      default:
        target: "0%"
    patch:
      default:
        target: "0%"
