# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
repos:
  # Autoformat: Python code, syntax patterns are modernized
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
        # check-tmp is a Python based test script run in created environments
        # that can be at least Python 3.5 even though we require Python 3.6 for
        # repo2docker itself.
        exclude: check-tmp

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --target-version=py36
          - --target-version=py37
          - --target-version=py38
          - --target-version=py39
          - --target-version=py310
          - --target-version=py311

  # Autoformat: Python code
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black

  # Autoformat: markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        files: ".md"
