dist: xenial
os: linux
language: python
cache: pip
services:
- docker
python:
- 3.8
install:
# Make a wheel and install it to test to catch possible
# issues with releases
- pip install --upgrade setuptools pip
- pip install -r dev-requirements.txt
- python setup.py bdist_wheel
- pip install dist/*.whl
- pip freeze
script:
- |
  # run autoformat
  if [[ "$REPO_TYPE" == "lint" ]]; then
    pre-commit run --all-files
  fi
after_success:
- pip install codecov
- pushd tests && codecov && popd

after_failure:
- |
  # point to auto-lint-fix
  echo "You can install pre-commit hooks to automatically run formatting"
  echo "on each commit with:"
  echo "    pre-commit install"
  echo "or you can run by hand on staged files with"
  echo "    pre-commit run"
  echo "or after-the-fact on already committed files with"
  echo "    pre-commit run --all-files"

deploy:
  provider: pypi
  username: mybinderteam
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: jupyterhub/repo2docker
  password:
    secure: ZkJTcI6fVkh2yRB0UVwSPVvGtfade7sQDZ6BjQR5bHRZuBLFq4/nxmn88BIPc6uYEHB6hxxfr9RbyP7ZnyUVUoTiyRfDM8kQe0RvFUVxRj7brZZFMYt6OTMiPUgWvyDqYIdVx+D5qgFgLxnQtUiZ0iqvPgQ+9Jn5SxZuuovrARpaTavlmKo4Vw63Ks/3zV61YeehvELFxU2Ibjy5ujMo/R119KZ7G3Z1w0IyJyVZQ9WaG1VXLO1LjFifpCcjMawaTJ9TmD5BOdF4IAIlP2QlB9N+v2xxuEGy7Mc9FwAH6M8kNqmjhe/ayj83vEMmlkxhE66unqiFJkSXzH1Rh8ythOy9s9qiDgeZeW/rYYLrzVNl9aMHicidV4PKEzobwXS/u8c/wx0fsAMNPcHY+O/8+hFLwy4ZLHusNiyCjPv5sVOq7yM/EKCjkod71bzFOvnnCZ70S0pxrR1nwEKo3x8qaK7l9aw0raSgWyrp6VHzEI4zPfBvP+R2ZYCUqBBj7rrpEl2C02AMKEkTh7Xm5LpaAFCBBMUwTATg7hECmB232vO+C6CLED+ONmGost5jOgsGwIun6viM5eXhP1tCeC5XeAtYozo/9UUIc5yHZL/8YtnmfCxvSi7p6h4qgLDCviKTH3bJCsRjF1ktkTiWAT+wL/SywsRz5D9tjV4b70neM8I=
